title: "My Python Resources Collection"
description: "A collection of Python resources I've found useful."
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

navigation:
  - name: "Home"
    link: "/"
  - name: "Tutorials"
    link: "/tutorials"
  - name: "Tips and Tricks"
    link: "/tips-and-tricks"
  - name: "Useful Links"
    link: "/links"
